export const CHANGE_IS_MOBILE = "CHANGE_IS_MOBILE";
export const CHANGE_WIDTH_AND_HEIGHT = "CHANGE_WIDTH_AND_HEIGHT";

export const CHANGE_PATH = "CHANGE_PATH";

export const CREATE_TEAM_MEMBER = "CREATE_TEAM_MEMBER";
export const UPDATE_TEAM_MEMBER = "UPDATE_TEAM_MEMBER";
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER";
